spring.application.name=transporte

spring.datasource.url=jdbc:oracle:thin:@vtuimca831glgtbz_high?TNS_ADMIN=/app/wallet
spring.datasource.username=ADMIN
spring.datasource.password=Backend12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

oracle.net.ssl_server_dn_match=true

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariPool

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.software.amazon.awssdk=DEBUG
logging.level.io.awspring.cloud=DEBUG

cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
cloud.aws.credentials.session-token=${AWS_SESSION_TOKEN}
cloud.aws.region.static=us-east-1
cloud.aws.stack.auto=false

aws.s3.bucket=transportebucket
aws.region=us-east-1

efs.path=/app/efs